name: Run checks

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NEXT_TELEMETRY_DISABLED: "1"

jobs:
  lint:
    runs-on: ubuntu-latest

    concurrency:
      group: lint
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup Node
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Run lint
        run: yarn lint
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: eslint-results.sarif

  check-types:
    runs-on: ubuntu-latest

    concurrency:
      group: check-types
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup Node
        uses: actions/setup-node@v6.1.0
        with:
          node-version: 24
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: yarn install

      - name: Run check-types
        run: yarn check-types
